"""
Django settings for example project.
Generated by 'django-admin startproject' using Django 1.11.9.
For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import re

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

from django.utils.translation import gettext_lazy as _

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "YOUR_SECRET_KEY"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SERVE_MEDIA = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.sites",
    "django.contrib.sessions",
    "django.contrib.staticfiles",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "suit",
    "fluentcms_suit",
    "django.contrib.admin",
    "fluent_pages",
    "fluent_pages.pagetypes.flatpage",
    "fluent_pages.pagetypes.fluentpage",
    "fluent_pages.pagetypes.redirectnode",
    "fluent_pages.pagetypes.textfile",
    "mptt",
    "polymorphic",
    "polymorphic_tree",
    "slug_preview",
    "parler",
    "fluent_contents",
    "fluent_contents.plugins.code",
    "fluent_contents.plugins.commentsarea",
    "fluent_contents.plugins.gist",
    "fluent_contents.plugins.googledocsviewer",
    "fluent_contents.plugins.iframe",
    "fluent_contents.plugins.markup",
    "fluent_contents.plugins.oembeditem",
    "fluent_contents.plugins.picture",
    "fluent_contents.plugins.rawhtml",
    "fluent_contents.plugins.sharedcontent",
    "fluent_contents.plugins.text",
    "any_urlfield",
    "any_imagefield",
    "django_wysiwyg",
    "tinymce",
]

import django

if "fluent_contents.plugins.commentsarea" in INSTALLED_APPS:
    if django.VERSION < (1, 7):
        INSTALLED_APPS += [
            "django.contrib.comments",
        ]
    else:
        INSTALLED_APPS += [
            "django_comments",
        ]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "example.urls"

SITE_ID = 1

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(os.path.dirname(__file__), "templates"),
            os.path.join(os.path.dirname(__file__), "templates", "layouts"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "example.wsgi.application"


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = "en"
LANGUAGES = (
    ("en", _("English")),
    ("es", _("Spanish")),
    ("fr", _("French")),
)

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# Absolute filesystem path to the directory that will hold user-uploaded files.
MEDIA_ROOT = os.path.join(os.path.dirname(__file__), "media")

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
MEDIA_URL = "/media/"

# Absolute path to the directory static files should be collected to.
STATIC_ROOT = os.path.join(os.path.dirname(__file__), "static")

STATIC_URL = "/static/"

FLUENT_PAGES_TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "templates", "layouts")
FLUENT_PAGES_PARENT_ADMIN_MIXIN = "fluentcms_suit.admin.FluentPagesParentAdminMixin"

DJANGO_WYSIWYG_FLAVOR = "tinymce"

PARLER_DEFAULT_LANGUAGE = LANGUAGE_CODE
PARLER_LANGUAGES = {
    SITE_ID: tuple({"code": lang[0]} for lang in LANGUAGES),
    "default": {
        "fallback": LANGUAGE_CODE,
        "hide_untranslated": False,
    },
}
